galaxyxone/ipfsStatViewerChrome

readme.md

more formatting 

---

DEVELOPMENT_DOCUMENTS.md

Added conversation and updated document data

document updates 

---

DEVELOPMENT_DOCUMENTS.md

You finished everything else, now finish this

fix this tomorrow

---

Go_To_Market.md

Added the initial go to market planning list

Go to market plan

---

dev-doc.md

File-size Zero Problem

---

readme.md

Work on this tonight and tomorrow

Tonight and tomorrow

---

dev-doc.md

Sprint finished

---

dev-doc.md

tiny little changes- figure the chrome extension out tonight

formatting changes

---

readme.md

Extension works on Chrome (Mac Embedded, Mac Intel, Linux Intel, Windows)

Formatting

---

readme.md

more documentation

---

readme.md

add future update(save treemap and display it even when ipfs is not on-

small changes

---

readme.md

make sure everything is as it should be

fixed version

---

readme.md

still waiting on chrome extension to pass review to be added into the chrome store

chrome extension review

---

readme.md

Go through and look at everything, make sure you got everything

improving install documentation

---

readme.md

Fixing up all the documentation- take a loot again at all the code

simple changes

---

projectNotes.md

Documentation Updates

---

readme.md

update on chrome

---

projectNotes.md

UI updates

---

readme.md

Add documentation encompassing recently finished Brave integration

documentation fixes

---

stat-viewer-grant-report.md

This is the start of the grant report for the project IPFSStatViewer

Grant Report

---

development/src/App.js

change this to were the titles resize too

title resize feature commented
